import type { Metadata } from "next";
import Providers from "@/components/Providers/Providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Quadrinhos Rei",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br">
      <body><Providers>{children}</Providers></body>
    </html>
  );
}
